spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
#    同步方式
    hibernate:
      ddl-auto: update
    show-sql: true

#日志的配置文件
logging:
  level:
    root: info
    com.autumn.blog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080
